services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=waldowautelet4@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  
  # update images in case new version available
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  backend:
    image: ghcr.io/whereisw4ldo/backend:master
    build:
      context: ./Backend/Backend.Api
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.backend.rule=Host(`waldo.today`) && PathPrefix(`/api`)"
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 2
  
  frontend:
    image: ghcr.io/whereisw4ldo/frontend:master
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`waldo.today`)"
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.entrypoints=websecure"
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"

volumes:
  letsencrypt: