services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure"
      - "--providers.docker"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # update images in case new version available
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  backend:
    image: ghcr.io/whereisw4ldo/backend:master
    build:
      context: ./Backend/Backend.Api
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.backend.rule=Host(`waldo.today`) && PathPrefix(`/api`)"
  
  frontend:
    image: ghcr.io/whereisw4ldo/frontend:master
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`waldo.today`)"