services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.websecure.http.tls.certResolver=myresolver"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=waldowautelet4@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  
  # update images in case new version available
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  backend:
    image: ghcr.io/whereisw4ldo/personalwebsite-backend:master
    build:
      context: ./Backend/Backend.Api
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.backend.rule=Host(`waldo.today`) && PathPrefix(`/api`)"
      - "traefik.enable=true"
    deploy:
      mode: replicated
      replicas: 2
  
  frontend:
    image: ghcr.io/whereisw4ldo/personalwebsite-frontend:master
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`waldo.today`)"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./Logging/otel-config.yaml:/etc/otel/config.yaml
    command:
      - '--config=/etc/otel/config.yaml'
    ports:
      - "4317:4317" #grpc
      - "4318:4318" #http
    depends_on:
      - loki
  
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh                                                                                                                                       
    image: grafana/grafana:latest     
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.waldo.today`)"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"

volumes:
  letsencrypt:
    