@Backend = http://localhost:5036
GET {{Backend}}/api/weatherforecast/
Accept: application/json


### Version
GET {{Backend}}/api/version


### Register
POST {{Backend}}/api/login/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### Login right credentials
POST {{Backend}}/api/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Login wrong credentials
POST {{Backend}}/api/login/
Content-Type: application/json

{
  "username": "admin",
  "password": "somethingElse"
}