name: Database Migration Update

on:
  push:
    branches: [ "master" ]

jobs:
  rerun-docker-compose:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute database migration
        run: |
          cd Backend
          source ~/.bashrc
          dotnet ef migrations add ${{ github.sha }} --project Database --startup-project Backend.Api
