name: Create and push docker image

on:
  push:
    paths:
      - 'compose.yml'
    branches: [ "master" ]

jobs:
  rerun-docker-compose:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run docker-compose
        run: docker-compose up -d