name: Update docker-compose

on:
  push:
    paths: [ "compose.yaml" ]
    branches: [ "master" ]

jobs:
  rerun-docker-compose:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run docker-compose
        run: docker-compose up -d